#ifndef _MUSQL_GDEFINE_H_
#define _MUSQL_GDEFINE_H_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#define MAX_PLAYER_EQUIPMENT 12	// need to redo agin aññ with this macro
#define TEST_FIX_MUUN 0

#define TEST_FIX_DARKRAVEN 1

#define ENABLE_SEASON12 1
#define OBJ_STARTUSERINDEX 1
#define OBJMAX MAXINT

// #ifndef MAX_ACCOUNT_LEN
#define MAX_ACCOUNT_LEN	10
#define MAX_GUILD_LEN	8
//#endif


#define	MAX_LUCKYINFO_LEVELRATE			16
#define MAX_LUCKYINFO_ITEMEQUIPMENT		8
#define	MAX_LUCKYINFO_SMELTRATE			10

#define MAX_CHAT_LEN 90

#define MAX_CANCEL_ITEMS_SALE	5


#define MAX_ITEM_IN_SHOP 120
#define MAX_ITEM_INFO 12
#define MAX_DBITEM_INFO 32

#define MAX_ITEM_IN_SHOP 120


#define MAX_ACCOUNT_LEN 10
#define MAX_TYPE_PLAYER 8
#define MAX_NUMBER_MAP 101

#define MAX_MONSTER_SEND_MSG	20
#define MAX_MONSTER_SEND_ATTACK_MSG 100
#define MAX_MONSTER_TYPE 1024
#define MAX_GUILD_LEN 8
#define MAX_CHARNAME_LEN 10
#define TRADE_BOX_SIZE 32
#define MAGIC_SIZE 150
#define INVETORY_WEAR_SIZE	12
#define INVENTORY_BAG_START INVETORY_WEAR_SIZE
#define TRADE_BOX_MAP_SIZE 32
#define PSHOP_SIZE 32
#define PSHOP_MAP_SIZE 32
#define PSHOP_START_RANGE 204
#define PSHOP_END_RANGE 236
#define MAX_SELF_DEFENSE 5
#define MAX_ST_HIT_DAMAGE 40
#define MAX_ZEN 2000000000
#define MAX_WAREHOUSE_ZEN	1000000000
#define ACTIVE_ITEM_SEARCH 0
#define CHAOS_BOX_SIZE 32
#define CHAOS_BOX_MAP_SIZE 32
#define MAX_BUFFEFFECT	32
#define MAX_MUUN_EFFECT_LIST 2

#define INVENTORY_SIZE				237	//-> 236
#define WAREHOUSE_SIZE				240	//-> 240
#define WAREHOUSE_BUFF				4096
#define MAIN_INVENTORY_SIZE			204	//-> 204
#define INVENTORY_MAP_SIZE			225	//-> 224
#define MAX_INVENTORY_H				24
#define MAX_INVENTORY_H2			28
#define MAX_INVENTORY_LEN			192
#define MAX_WAREHOUSE_H				30
#define MUUN_INVENTORY_SIZE			62
#define EVENT_INVENTORY_SIZE		32
#define EVENT_INVENTORY_MAP_SIZE	32

#define MAX_CS_GUILDLIST 100
#define MAX_CS_NPC 200
#define PMHC_WORD 0xC2
#define MAX_IDSTRING 10

#define MAX_USER		1500
#define MAX_IO_THREAD_HANDLES	16
#define HIDE_ERRORL10
#define MAX_EXSENDBUF_SIZE 14048
#define MAX_IO_BUFFER_SIZE		32768


#endif
