
#ifndef _MUSQL_H_REVISION
#define _MUSQL_H_REVISION
    #define REVISION_NR "1"

    #define CONNECT_DB_VERSION_NR 1
    #define CONNECT_DB_STRUCTURE_NR 1
    #define CONNECT_DB_CONTENT_NR 001
    #define CONNECT_DB_UPDATE_DESCRIPTION " "

#endif // __REVISION_H__
