DELIMITER $$
CREATE PROCEDURE `IGC_ArcaBattleAllMarkCntSelect`()
BEGIN     
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SELECT G_Name, MarkCnt FROM IGC_ARCA_BATTLE_GUILDMARK_REG;
END$$
DELIMITER ;
