DELIMITER $$
CREATE PROCEDURE `IGC_ArcaBattleAllJoinUserSelect`()
BEGIN  
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

BEGIN
	SELECT G_Name, Number, CharName
	FROM	IGC_ARCA_BATTLE_MEMBER_JOIN_INFO;
END;

/* SET XACT_ABORT OFF; */
END$$
DELIMITER ;
