#ifndef _GAMEPROTOCOL_H
#define _GAMEPROTOCOL_H

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "StdAfx.h"
//#include "ProtocolStructs.h"
#include "Database/Query.h"


struct CSP_ANS_GUILDREGINFO;
struct CSP_ANS_GUILDREGMARK;
struct PMSG_ACTION;
struct PMSG_ACTIONRESULT;
struct PMSG_ADDON_REQUEST;
struct PMSG_ADDSTATS_RESULT;
struct PMSG_ADDSTATS;
struct PMSG_AGILITYSEND;
struct PMSG_AHINFO;
struct PMSG_ALTERPSHOPVAULT;
struct PMSG_ANTIHACK_BREACH;
struct PMSG_ANTIHACK_CHECK;
struct PMSG_ATTACK;
struct PMSG_ATTACKRESULT;
struct PMSG_ATTACKSPEEDSEND;
struct PMSG_BEATTACK_COUNT;
struct PMSG_BEATTACK;
struct PMSG_BLOCKCHAT_LIST;
struct PMSG_BUYREQUEST;
struct PMSG_BUYRESULT;
struct PMSG_CALLMONSTER_VIEWPORTCREATE;
struct PMSG_CCF_UI_ONOFF;
struct PMSG_CHAIN_MAGIC_OBJECT;
struct PMSG_CHAIN_MAGIC;
struct PMSG_CHAOSMIX;
struct PMSG_CHARCHECK_RESULT;
struct PMSG_CHARCHECK;
struct PMSG_CHARCREATE;
struct PMSG_CHARCREATERESULT;
struct PMSG_CHARDELETE;
struct PMSG_CHARLIST;
struct PMSG_CHARLISTCOUNT;
struct PMSG_CHARMAPJOIN;
struct PMSG_CHATDATA_NUMBER;
struct PMSG_CHATDATA_WHISPER;
struct PMSG_CHATDATA;
struct PMSG_CHECK_MAINEXE_RESULT;
struct PMSG_CHECK_MAINEXE;
struct PMSG_CLIENTCLOSE;
struct PMSG_CLIENTMSG;
struct PMSG_CLIENTTIME;
struct PMSG_CSATTKGUILDLIST;
struct PMSG_DEL_PENTAGRAMJEWEL;
struct PMSG_DEL_PSHOPITEM;
struct PMSG_DISABLE_RECONNECT;
struct PMSG_DSF_PLAY_STATE;
struct PMSG_DSF_RESULT;
struct PMSG_DSF_STATE;
struct PMSG_DSF_TEAM_USERNAME;
struct PMSG_DURATION_MAGIC_RECV;
struct PMSG_DURATION_MAGIC_SEND;
struct PMSG_ELEMENTALDAMAGE;
struct PMSG_ENTER_ZONE_RESULT;
struct PMSG_EQUIPMENTLIST;
struct PMSG_EVENT_INVEN_ITEM_MOD;
struct PMSG_EVENT;
struct PMSG_EVENTENTRY_NOTICE;
struct PMSG_EVENTINVENTORY_DELETE;
struct PMSG_EVENTITEM_DUR;
struct PMSG_EVENTITEM_GETREQUEST;
struct PMSG_EVENTITEM_GETRESULT;
struct PMSG_EVENTITEM_THROW_RESULT;
struct PMSG_EVENTITEM_THROW;
struct PMSG_EX_GAMESERVER_MOVE_RESULT;
struct PMSG_EX_GAMESERVER_MOVE_SEND;
struct PMSG_EX_SKILL_COUNT;
struct PMSG_EXCHANGE_EVENTCHIP;
struct PMSG_GETMUTONUMBER;
struct PMSG_GOALSEND;
struct PMSG_GUILD_ASSIGN_STATUS_REQ;
struct PMSG_GUILD_ASSIGN_STATUS_RESULT;
struct PMSG_GUILD_ASSIGN_TYPE_REQ;
struct PMSG_GUILD_ASSIGN_TYPE_RESULT;
struct PMSG_GUILDCREATED_RESULT;
struct PMSG_GUILDDELUSER;
struct PMSG_GUILDINFOSAVE;
struct PMSG_GUILDJOINQ;
struct PMSG_GUILDMASTERANSWER;
struct PMSG_GUILDQRESULT;
struct PMSG_GUILDVIEWPORT_USER;
struct PMSG_GUILDVIEWPORT;
struct PMSG_GUILDWARSEND_RESULT;
struct PMSG_HELLO;
struct PMSG_IDPASS;
struct PMSG_ILLUSION_TEMPLE_USE_MAGIC_RESULT;
struct PMSG_INSERT_PENTAGRAMJEWEL;
struct PMSG_INVENTORYITEMMODIFY;
struct PMSG_INVENTORYITEMMOVE_RESULT;
struct PMSG_INVENTORYITEMMOVE;
struct PMSG_INVENTORYLIST;
struct PMSG_INVENTORYLISTCOUNT;
struct PMSG_ITEMDURREPAIR;
struct PMSG_ITEMGETREQUEST;
struct PMSG_ITEMGETRESULT;
struct PMSG_ITEMTHROW_RESULT;
struct PMSG_ITEMTHROW;
struct PMSG_ITEMVIEWPORTCREATE;
struct PMSG_ITL_GUILD_RANKINFO;
struct PMSG_ITL_PLAY_STATE;
struct PMSG_ITL_RELICS_GET_USER;
struct PMSG_ITL_RESULT;
struct PMSG_ITL_SKILL_END;
struct PMSG_ITL_STATE;
struct PMSG_ITL_STONEINFO;
struct PMSG_ITL_USE_MAGIC_RESULT;
struct PMSG_ITL_USER_ADD_EXP;
struct PMSG_ITR_RESULT;
struct PMSG_ITR_USER_ADD_EXP;
struct PMSG_JOINRESULT;
struct PMSG_KICKOUT_UNIONMEMBER_REQ;
struct PMSG_KILLCOUNT;
struct PMSG_KILLPLAYER_EXT;
struct PMSG_LEVELUP;
struct PMSG_LOGINSEVER_LIVE;
struct PMSG_LUCKYITME_DB_INFO;
struct PMSG_LVPOINTADD;
struct PMSG_LVPOINTADDRESULT;
struct PMSG_MAGICATTACK_RESULT;
struct PMSG_MAGICATTACK;
struct PMSG_MAGICCANCEL;
struct PMSG_MAGICLIST;
struct PMSG_MAGICLISTCOUNT;
struct PMSG_MAPMOVE_CHECKSUM;
struct PMSG_MEMBER_POS_INFO_SEND;
struct PMSG_MONEY;
struct PMSG_MONSTER_VIEWPORTCREATE;
struct PMSG_MOVE_PSHOPITEM;
struct PMSG_MOVE;
struct PMSG_MUBOT_REQ_START;
struct PMSG_MUBOT_SETTINGS_RECV;
struct PMSG_MUBOT_USE;
struct PMSG_MUUN_ATTACK_COMMAND;
struct PMSG_MUUN_INVEN_ITEM_MOD;
struct PMSG_MUUN_INVEN_SUB_EQUIP_OPEN;
struct PMSG_MUUN_ITEM_SELLREQUEST;
struct PMSG_MUUN_ITEM_SELLRESULT;
struct PMSG_MUUN_RIDE_SELECT;
struct PMSG_MUUNITEM_CONDITION_STATUS;
struct PMSG_MUUNITEM_DUR;
struct PMSG_MUUNITEM_GETREQUEST;
struct PMSG_MUUNITEM_GETRESULT;
struct PMSG_NOTIFY_MAXUSER;
struct PMSG_NOTIFY_OBJECT_CREATION_STATE;
struct PMSG_NOTIFY_ZONE_CLEAR;
struct PMSG_NOTIFY_ZONE_TIME;
struct PMSG_OBJECT_LIFE_INFO;
struct PMSG_PACKETCHECKSUM;
struct PMSG_PARTYDELUSER;
struct PMSG_PARTYLIST;
struct PMSG_PARTYLISTCOUNT;
struct PMSG_PARTYREQUEST;
struct PMSG_PARTYREQUESTRESULT;
struct PMSG_PENTAGRAM_JEWEL_INOUT;
struct PMSG_PENTAGRAMJEWEL_INFO;
struct PMSG_PETINVENTORY_DELETE;
struct PMSG_PING_RESULT;
struct PMSG_PKLEVEL;
struct PMSG_POSISTION_SET;
struct PMSG_POST_DATA;
struct PMSG_PRICE_INFO;
struct PMSG_PRICE_ITEM_LIST;
struct PMSG_PROPERTYITEMCOUNT;
struct PMSG_PROPERTYITEMINFO;
struct PMSG_RAGE_ATTACK_RANGE_ANS;
struct PMSG_RAGE_ATTACK_RANGE;
struct PMSG_RAGEATTACK_REQ;
struct PMSG_RAGEATTACK;
struct PMSG_RANKING_SET;
struct PMSG_RAREITEMPIRCESEND;
struct PMSG_RECALLMONLIFE;
struct PMSG_RECV_CHATDATA_WHISPER;
struct PMSG_RECV_DC_OTHER_CHANNEL;
struct PMSG_RECV_POSISTION_SET;
struct PMSG_RECV_TRAP;
struct PMSG_RECVMOVE;
struct PMSG_REGEVENTCHIP;
struct PMSG_RELATIONSHIP_JOIN_BREAKOFF_ANS;
struct PMSG_RELATIONSHIP_JOIN_BREAKOFF_REQ;
struct PMSG_REQ_2ANIV_SERIAL;
struct PMSG_REQ_2ANIV_SERIAL;
struct PMSG_REQ_2ANV_LOTTO_EVENT;
struct PMSG_REQ_ACCEPTENTER_ITR;
struct PMSG_REQ_ACCEPTMEMBER_PARTYMATCHING;
struct PMSG_REQ_ALLOW_JOIN_GUILDMATCHING;
struct PMSG_REQ_ALLOWLIST_GUILDMATCHING;
struct PMSG_REQ_ARCA_BATTLE_JOIN;
struct PMSG_REQ_BLOODCASTLE_ENTERCOUNT;
struct PMSG_REQ_BUY_PCPOINTSHOP;
struct PMSG_REQ_CANCEL_GUILDMATCHINGLIST;
struct PMSG_REQ_CANCEL_JOIN_PARTYMATCHING;
struct PMSG_REQ_CASTLESIEGESTATE;
struct PMSG_REQ_CCF_RANKING;
struct PMSG_REQ_CHAOS_MULTIMIX_CHECK;
struct PMSG_REQ_CL_ENTERCOUNT;
struct PMSG_REQ_CLASSDEF;
struct PMSG_REQ_CRCDATA;
struct PMSG_REQ_CRYWOLF_ALTAR_CONTRACT;
struct PMSG_REQ_CRYWOLF_BENEFIT_PLUS_CHAOSRATE;
struct PMSG_REQ_CRYWOLF_INFO;
struct PMSG_REQ_CSATTKGUILDLIST;
struct PMSG_REQ_CSCOMMAND;
struct PMSG_REQ_CSGATEOPERATE;
struct PMSG_REQ_CSHUNTZONEENTER;
struct PMSG_REQ_CSREGGUILDLIST;
struct PMSG_REQ_DELETE_STONES;
struct PMSG_REQ_DELETE_STONES;
struct PMSG_REQ_DEVILSQUARE_REMAINTIME;
struct PMSG_REQ_DSF_ACCEPTENTER;
struct PMSG_REQ_DSF_CAN_PARTY_ENTER;
struct PMSG_REQ_DSF_GET_REWARD;
struct PMSG_REQ_DSF_GO_FINAL_PARTY_INFO;
struct PMSG_REQ_DSF_GO_FINAL_PARTY;
struct PMSG_REQ_DSF_PARTYRANKRENEW;
struct PMSG_REQ_DUEL_EXIT;
struct PMSG_REQ_DUEL_INVITE;
struct PMSG_REQ_DUEL_JOINCNANNEL;
struct PMSG_REQ_DUEL_LEAVECNANNEL;
struct PMSG_REQ_END_DUEL;
struct PMSG_REQ_ENTER_DOPPELGANGER;
struct PMSG_REQ_ENTER_ITR;
struct PMSG_REQ_ENTER_KANTURU_BOSS_MAP;
struct PMSG_REQ_ENTER_ZONE;
struct PMSG_REQ_EVENTENTRY_INFO;
struct PMSG_REQ_EVOMON_MAXSCORE;
struct PMSG_REQ_GET_DSF_REWARD;
struct PMSG_REQ_GET_PARTYMATCHINGLIST;
struct PMSG_REQ_GET_REWARD;
struct PMSG_REQ_GET_UBF_REAL_NAME;
struct PMSG_REQ_GIVEUPCASTLESIEGE;
struct PMSG_REQ_GUILD_PERIODBUFF_DELETE;
struct PMSG_REQ_GUILD_PERIODBUFF_INSERT;
struct PMSG_REQ_GUILDMARK_OF_CASTLEOWNER;
struct PMSG_REQ_GUILDMATCHINGLIST;
struct PMSG_REQ_GUILDMATCHINGLISTSEARCHWORD;
struct PMSG_REQ_GUILDREGINFO;
struct PMSG_REQ_GUILDVIEWPORT;
struct PMSG_REQ_ILLUSIONTEMPLE_ENTERCOUNT;
struct PMSG_REQ_IN_PENTAGRAM_JEWEL;
struct PMSG_REQ_ITL_RELATE_RELICS;
struct PMSG_REQ_JEWEL_MIX;
struct PMSG_REQ_JEWEL_UNMIX;
struct PMSG_REQ_JOIN_GUILDMATCHING;
struct PMSG_REQ_KANTURU_STATE_INFO;
struct PMSG_REQ_LUCKYCOIN_REGISTER;
struct PMSG_REQ_LUCKYCOIN_TRADE;
struct PMSG_REQ_LUCKYCOIN;
struct PMSG_REQ_LUCKYITEM_DELETE;
struct PMSG_REQ_LUCKYITEM_INSERT_2ND;
struct PMSG_REQ_LUCKYITEM_INSERT;
struct PMSG_REQ_LUCKYITEM_SELECT;
struct PMSG_REQ_MAPMOVE;
struct PMSG_REQ_MAPSERVERAUTH;
struct PMSG_REQ_MAPSVRAUTH;
struct PMSG_REQ_MAPSVRMOVE;
struct PMSG_REQ_MASTERLEVEL_SKILL;
struct PMSG_REQ_MEMBERJOIN_PARTYMATCHINGLIST;
struct PMSG_REQ_MEMBERJOIN_STATELIST_PARTYMATCHING;
struct PMSG_REQ_MINETWINKLE_REWARD;
struct PMSG_REQ_MINETWINKLE;
struct PMSG_REQ_MINIMAPDATA;
struct PMSG_REQ_MONEYDRAWOUT;
struct PMSG_REQ_MOVE_OTHERSERVER;
struct PMSG_REQ_MOVE_TO_CASTLE_HUNTZONE;
struct PMSG_REQ_MOVEBLOODCASTLE;
struct PMSG_REQ_MOVECHAOSCASTLE;
struct PMSG_REQ_MOVEDEVILSQUARE;
struct PMSG_REQ_MOVEILLUSIONTEMPLE;
struct PMSG_REQ_MUUN_EXCHANGE;
struct PMSG_REQ_NPC_POSITION;
struct PMSG_REQ_NPCBUY;
struct PMSG_REQ_NPCDBLIST;
struct PMSG_REQ_NPCREPAIR;
struct PMSG_REQ_NPCUPGRADE;
struct PMSG_REQ_OPEN_PCPOINTSHOP;
struct PMSG_REQ_OUT_PENTAGRAM_JEWEL;
struct PMSG_REQ_PENTAGRAMJEWEL;
struct PMSG_REQ_PERIODBUFF_DELETE;
struct PMSG_REQ_PERIODBUFF_INSERT;
struct PMSG_REQ_PERIODBUFF_SELECT;
struct PMSG_REQ_PERIODITEMEX_DELETE;
struct PMSG_REQ_PERIODITEMEX_INSERT;
struct PMSG_REQ_PERIODITEMEX_SELECT;
struct PMSG_REQ_PSHOPITEMVALUE_INFO;
struct PMSG_REQ_QUESTEXP_INFO;
struct PMSG_REQ_REFINE_PENTAGRAM_JEWEL;
struct PMSG_REQ_REG_CC_OFFLINE_GIFT;
struct PMSG_REQ_REG_DL_OFFLINE_GIFT;
struct PMSG_REQ_REG_HT_OFFLINE_GIFT;
struct PMSG_REQ_REG_RINGGIFT;
struct PMSG_REQ_REG_WANTED_PARTYMEMBER;
struct PMSG_REQ_REGCASTLESIEGE;
struct PMSG_REQ_REGGUILDMARK;
struct PMSG_REQ_REGGUILDMATCHINGDATA;
struct PMSG_REQ_REGISTER_EVENTCHIP;
struct PMSG_REQ_REGISTER_LUCKYCOIN;
struct PMSG_REQ_REGISTER_STONES;
struct PMSG_REQ_REPOSUSER_IN_CC;
struct PMSG_REQ_REPOSUSER_IN_CCF;
struct PMSG_REQ_RESET_EVENTCHIP;
struct PMSG_REQ_RESET_EVENTCHIP;
struct PMSG_REQ_RUUD_STORE_BUYITEM;
struct PMSG_REQ_SANTACHECK;
struct PMSG_REQ_SANTAGIFT;
struct PMSG_REQ_SAVE_DSF_PARTYPOINT;
struct PMSG_REQ_SAVE_DSF_REWARD_USER;
struct PMSG_REQ_SAVE_EVOMON_RESULT;
struct PMSG_REQ_SET_DSF_WINNER_INFO;
struct PMSG_REQ_SETPENTAGRAMJEWEL;
struct PMSG_REQ_START_DUEL;
struct PMSG_REQ_STOPMINIMAPDATA;
struct PMSG_REQ_SWITCHWARE;
struct PMSG_REQ_TAXMONEYINFO;
struct PMSG_REQ_TAXRATECHANGE;
struct PMSG_REQ_UBF_ACCOUNT_USERINFO;
struct PMSG_REQ_UBF_CANCEL;
struct PMSG_REQ_UBF_GET_REWARD;
struct PMSG_REQ_UBF_INFO;
struct PMSG_REQ_UBF_JOIN;
struct PMSG_REQ_UBF_REAL_NAME;
struct PMSG_REQ_UBF_SET_RECEIVED_REWARD;
struct PMSG_REQ_UPGRADE_PENTAGRAM_JEWEL;
struct PMSG_REQ_USE_BOX;
struct PMSG_REQ_USEILLUSIONTEMPLESKILL;
struct PMSG_REQ_USETRANSFORMATIONRING;
struct PMSG_REQ_USEWEAPON;
struct PMSG_REQ_VIEW_EC_MN;
struct PMSG_REQ_VIEW_EC_MN;
struct PMSG_REQ_WAITLIST_PARTYMATCHING;
struct PMSG_REQ_WEAPON_DAMAGE_VALUE;
struct PMSG_REQUEST_PET_ITEM_COMMAND;
struct PMSG_REQUEST_PET_ITEMINFO;
struct PMSG_RES_EXPEVENTINFO;
struct PMSG_RESULT_CCF_ENTERCHECK;
struct PMSG_RESULT_MOVEBLOODCASTLE;
struct PMSG_RESULT;
struct PMSG_RSA_KEY;
struct PMSG_RUUD;
struct PMSG_SELLREQUEST;
struct PMSG_SEND_AH_INFO;
struct PMSG_SEND_CCF_INFO_ALL_SVR;
struct PMSG_SEND_EVENT_BANNER;
struct PMSG_SEND_HITHACK_INFO;
struct PMSG_SEND_MUUN_RIDE_VIEWPORT_INFO;
struct PMSG_SEND_NEWS;
struct PMSG_SEND_PCPOINT;
struct PMSG_SERVERCMD;
struct PMSG_SERVERINFO;
struct PMSG_SERVERLIST_SERVER;
struct PMSG_SERVERMSG;
struct PMSG_SERVERSLIST_COUNT;
struct PMSG_SET_CHAT_COLOR;
struct PMSG_SET_DEVILSQUARE;
struct PMSG_SET_OFFTRADE;
struct PMSG_SETAGILITYBUG;
struct PMSG_SETCHARSET;
struct PMSG_SETQUEST;
struct PMSG_SHOPITEMCOUNT;
struct PMSG_SIMPLE_GUILDVIEWPORT_COUNT;
struct PMSG_SIMPLE_GUILDVIEWPORT;
struct PMSG_SKILLKEY;
struct PMSG_STAT_BONUS;
struct PMSG_STATEBLOODCASTLE;
struct PMSG_STATS_RESULT;
struct PMSG_SUMMONER_INFO;
struct PMSG_TALKREQUEST;
struct PMSG_TALKRESULT;
struct PMSG_TARGET_HP_DELETE;
struct PMSG_TARGET_HP_INFO;
struct PMSG_TARGET_HP;
struct PMSG_TARGET_TELEPORT;
struct PMSG_TELEPORT_RESULT;
struct PMSG_TELEPORT;
struct PMSG_TIMEVIEW;
struct PMSG_TRADE_GOLD;
struct PMSG_TRADE_OKBUTTON;
struct PMSG_TRADE_REQUEST;
struct PMSG_TRADE_RESPONSE;
struct PMSG_UBF_ACCOUNT_USER_COPY_PETITEM;
struct PMSG_UBF_ACCOUNT_USER_COPY_RESULT;
struct PMSG_UBF_ACCOUNT_USER_COPY;
struct PMSG_UBF_ANS_CANCEL_REGISTER_USER;
struct PMSG_UBF_COPY_PETITEM;
struct PMSG_UBF_REGISTER_ACCOUNT_USER_RESULT;
struct PMSG_UBF_REGISTER_ACCOUNT_USER;
struct PMSG_UBF_REQ_CANCEL_REGISTER_USER;
struct PMSG_UNIONLIST_REQ;
struct PMSG_UPDATE_PSHOPITEMVALUE_INFO;
struct PMSG_USE_STAT_FRUIT;
struct PMSG_USEEXPANSIONITEM;
struct PMSG_USEITEM_MUUN_INVEN_RESULT;
struct PMSG_USEITEM_MUUN_INVEN;
struct PMSG_USEITEM;
struct PMSG_USER_MUUN_EQUIPMENT_CHANGED;
struct PMSG_USEREQUIPMENTCHANGED;
struct PMSG_VIEWPORTCREATE_CHANGE;
struct PMSG_VIEWPORTCREATE;
struct PMSG_VIEWPORTDESTROY;
struct PMSG_WAREHOUSEMONEYINOUT;
struct PMSG_WAREHOUSEPASSSEND;
struct PMSG_ANS_DUEL_ANSWER;
struct PMSG_ANS_DUEL_OK;
struct PMSG_GENS_REWARD_CODE;
struct PMSG_REQ_ACHERON_ENTER;
struct PMSG_REQ_ARCA_BATTLE_ENTER;
struct PMSG_REQ_DUEL_EXIT;
struct PMSG_REQ_DUEL_JOINCNANNEL;
struct PMSG_REQ_DUEL_LEAVECNANNEL;
struct PMSG_REQ_GENS_INFO;
struct PMSG_REQ_INVENTORY_EQUIPMENT_ITEM;
struct PMSG_REQ_NIXIELAKE_ENTER;
struct PMSG_REQ_REG_GENS_MEMBER;
struct PMSG_REQ_SEGEDE_GENS_MEMBER;
struct PMSG_SEND_PET_ITEMINFO;
struct Recv_PetItem_Info;
struct SHOP_DATA;


class GameProtocol
{
public:

	GameProtocol();
	~GameProtocol();

	void ProtocolCore(BYTE protoNum, BYTE* aRecv, int aLen, CGameObject &Obj, BOOL Encrypt);
	void MsgSendV2(CGameObject &Obj, BYTE* Msg, int size);
	//void ChatSendV2(CGameObject &Obj, BYTE* Msg, int size);
	void CGLiveClient(PMSG_CLIENTTIME* lpClientTime, short aIndex);
	void GCCheckMainExeKeySend(CGameObject &Obj);
	WORD EncryptCheckSumKey(WORD wSource);
	void CGCheckMainRecv(PMSG_CHECK_MAINEXE_RESULT* lpMsg, CGameObject &Obj);
	void PEchoProc(BYTE* aMsg, int aLen, short aIndex);
	void GCResultSend(CGameObject &Obj, BYTE headcode, BYTE result);
	void ChatSend(CGameObject &Obj, char* szChat);
	void vChatSend(CGameObject &Obj, char* szChat, ...);
	void AllSendServerMsg(char* chatmsg);
	void DataSendAll(BYTE* lpMsg, int iMsgSize);
	void ChatTargetSend(CGameObject &Obj, char* szChat, int senduser);
	void PChatProc(PMSG_CHATDATA* lpChat, short aIndex);
	void CGChatRecv(PMSG_CHATDATA_NUMBER* lpMsg, CGameObject &Obj);
	void GCServerMsgSend(BYTE msg, CGameObject &Obj);
	void GCServerMsgStringSend(char* szMsg, CGameObject &Obj, BYTE type);
	void GCServerMsgStringSendEx(CGameObject &Obj, BYTE type, LPSTR szMsg, ...);
	void GCServerMsgStringSendAll(LPSTR  szMsg, BYTE type);
	void GCServerMsgStringSendAllEx(BYTE type, LPSTR szMsg, ...);
	void GCServerMsgStringSendGuild(GUILD_INFO_STRUCT &lpNode, char* szMsg, BYTE type);
	void GCEventStateSend(CGameObject &Obj, BYTE state, BYTE event);
	void GCMapEventStateSend(int map, BYTE state, BYTE event);
	void CGChatWhisperRecv(PMSG_CHATDATA_WHISPER* lpMsg, CGameObject &Obj);
	void SCPJoinResultSend(CGameObject &Obj, BYTE result);
	void CSPJoinIdPassRequest(PMSG_IDPASS* lpMsg, CGameObject &Obj);
	void GCJoinBillCheckSend(char* AccountId, CGameObject &Obj);
	void GCJoinResult(BYTE result, CGameObject &Obj);
	void GCJoinSocketResult(BYTE result, SOCKET Socket);
	void CGClientCloseMsg(PMSG_CLIENTCLOSE* lpMsg, CGameObject &Obj);
	void GCCloseMsgSend(CGameObject &Obj, BYTE result);
	void CGClientMsg(PMSG_CLIENTMSG* lpMsg, CGameObject &Obj);
	void CGPCharacterCreate(PMSG_CHARCREATE* lpMsg, CGameObject &Obj);
	void CGPCharDel(PMSG_CHARDELETE* lpMsg, CGameObject &Obj);
	void CGPCharacterMapJoinRequest(PMSG_CHARMAPJOIN* lpMsg, CGameObject &Obj);
	void GCLevelUpMsgSend(CGameObject &Obj, int iSendEffect);
	void CGLevelUpPointAdd(PMSG_LVPOINTADD* lpMsg, CGameObject &Obj);
	void GCInventoryItemOneSend(CGameObject &Obj, int pos);
	void GCPkLevelSend(CGameObject &Obj, BYTE pklevel);
	void GCMagicListOneSend(CGameObject &Obj, char Pos, WORD type, BYTE level, WORD skill, BYTE btListType);
	void GCMagicListOneDelSend(CGameObject &Obj, char Pos, WORD type, BYTE level, WORD skill, BYTE btListType);
	void GCMagicListMultiSend(CGameObject &Obj, BYTE btListType);
	void GCEquipmentSend(CGameObject &Obj);
	void GCRecallMonLife(CGameObject &Obj, int maxlife, int life);
	void GCTimeViewSend(CGameObject &Obj, int second);
	void GCGoalSend(CGameObject &Obj, char* Name1, BYTE score1, char* Name2, BYTE score2);
	void GCSkillKeyRecv(PMSG_SKILLKEY* lpMsg, CGameObject &Obj);
	void GCSkillKeySend(CGameObject &Obj, BYTE* keybuffer, BYTE GO, BYTE Qk, BYTE Wk, BYTE Ek, /*<regrel ebp+0x20>*/ /*|0x1|*/ BYTE ChatWnd, BYTE Rk, int QWER);
	void GCMoneySend(CGameObject &Obj, unsigned long money);
	void GCItemObjectInventoryPutSend(CGameObject &Obj, BYTE result, BYTE iteminfo1, BYTE iteminfo2);
	void CGItemGetRequest(PMSG_ITEMGETREQUEST* lpMsg, CGameObject &Obj, BYTE ID, BYTE ID1);
	bool CGItemDropRequest(PMSG_ITEMTHROW* lpMsg, CGameObject &Obj, int drop_type);
	void GCItemObjectMoveResultSend(CGameObject &Obj, BYTE result, BYTE pos, BYTE* const ItemInfo);
	void CGInventoryItemMove(PMSG_INVENTORYITEMMOVE* lpMsg, CGameObject &Obj);
	void GCEquipmentChange(CGameObject &Obj, int pos);
	void CGTalkRequestRecv(PMSG_TALKREQUEST* lpMsg, CGameObject &Obj);
	void GCUserWarehouseSend(CGameObject &Obj);
	void CGBuyRequestRecv(PMSG_BUYREQUEST* lpMsg, CGameObject &Obj);
	void CGSellRequestRecv(PMSG_SELLREQUEST* lpMsg, CGameObject &Obj);
	int  GetNeedMoneyItemDurRepaire(/*CGameObject &Obj, */class CItemObject* DurItem, int RequestPos);
	void ItemDurRepaire(CGameObject &Obj, /*CGameObject &Obj, */class CItemObject* DurItem, int pos, int RequestPos);
	void CGModifyRequestItem(PMSG_ITEMDURREPAIR* lpMsg, CGameObject &Obj);
	void CGTradeRequestSend(PMSG_TRADE_REQUEST* lpMsg, CGameObject &Obj);
	void CGTradeResponseRecv(PMSG_TRADE_RESPONSE* lpMsg, CGameObject &Obj);
	bool GCTradeResponseSend(BYTE response, CGameObject &Obj, LPSTR id, WORD level, int GuildNumber);
	int GCTradeOtherDel(CGameObject &Obj, BYTE tradeindex);
	int GCTradeOtherAdd(CGameObject &Obj, BYTE tradeindex, LPBYTE iteminfo);
	void CGTradeMoneyRecv(PMSG_TRADE_GOLD* lpMsg, CGameObject &Obj);
	bool GCTradeMoneyOther(CGameObject &Obj, DWORD money);
	bool GCTradeOkButtonSend(CGameObject &Obj, BYTE flag);
	void CGTradeOkButtonRecv(PMSG_TRADE_OKBUTTON* lpMsg, CGameObject &Obj);
	void CGTradeCancelButtonRecv(CGameObject &Obj);
	void CGTradeResult(CGameObject &Obj, BYTE result);
	void CGPartyRequestRecv(PMSG_PARTYREQUEST* lpMsg, CGameObject &Obj);
	void CGPartyRequestResultRecv(PMSG_PARTYREQUESTRESULT* lpMsg, CGameObject &Obj);
	void CGPartyList(CGameObject &Obj);
	void CGPartyListAll(int pnumber);
	void CGPartyDelUser(PMSG_PARTYDELUSER* lpMsg, CGameObject &Obj, int nType);
	void GCPartyDelUserSend(CGameObject &Obj);
	void GCPartyDelUserSendNoMessage(CGameObject &Obj);
	void CGGuildRequestRecv(PMSG_GUILDJOINQ* lpMsg, CGameObject &Obj);
	void CGGuildRequestResultRecv(PMSG_GUILDQRESULT* lpMsg, CGameObject &Obj);
	void CGGuildListAll(int pnumber);
	void CGGuildDelUser(PMSG_GUILDDELUSER* lpMsg, CGameObject &Obj);
	void GCGuildDelUserResult(CGameObject &Obj, BYTE Result);
	void GCGuildMasterQuestionSend(CGameObject &Obj);
	void CGGuildMasterAnswerRecv(PMSG_GUILDMASTERANSWER* lpMsg, CGameObject &Obj);
	void GCGuildMasterManagerRun(CGameObject &Obj);
	void CGGuildMasterInfoSave(CGameObject &Obj,PMSG_GUILDINFOSAVE* lpMsg);
	void CGGuildMasterCreateCancel(CGameObject &Obj);
	void GCGuildViewportNowPaint(CGameObject &Obj, char* guildname, BYTE* Mark, int isGuildMaster);
	void GCGuildViewportDelNow(CGameObject &Obj, int isGuildMaster);
	void GCManagerGuildWarEnd(char* GuildName);
	void GCManagerGuildWarSet(char* GuildName1, char* GuildName2, int type);
	void GCGuildWarRequestResult(char* GuildName, CGameObject &Obj, int type);
	void GCGuildWarRequestSend(char* GuildName, CGameObject &Obj, int type);
	void GCGuildWarRequestSendRecv(PMSG_GUILDWARSEND_RESULT* lpMsg, CGameObject &Obj);
	void GCGuildWarDeclare(CGameObject &Obj, char* _guildname);
	void GCGuildWarEnd(CGameObject &Obj, BYTE result, char* _guildname);
	void GCGuildWarScore(CGameObject &Obj);
	void CGWarehouseMoneyInOut(CGameObject &Obj,PMSG_WAREHOUSEMONEYINOUT* lpMsg);
	void GCWarehouseInventoryMoneySend(CGameObject &Obj, BYTE result, int money, int wmoney);
	void CGWarehouseUseEnd(CGameObject &Obj);
	void GCWarehouseStateSend(CGameObject &Obj, BYTE state);
	void GCWarehouseRecivePassword(CGameObject &Obj,PMSG_WAREHOUSEPASSSEND* lpMsg);
	void GCUserChaosBoxSend(CGameObject &Obj, int iChaosBoxType);
	void CGChaosBoxItemMixButtonClick(PMSG_CHAOSMIX* aRecv, CGameObject &Obj);
	void CGChaosBoxUseEnd(CGameObject &Obj);
	void PMoveProc(PMSG_MOVE* lpMove, CGameObject &Obj);
	void RecvPositionSetProc(PMSG_POSISTION_SET* lpMove, CGameObject &Obj);
	void CGAttack(PMSG_ATTACK* lpMsg, CGameObject &Obj);
	void GCDamageSendPoison(CGameObject &Obj, int damage, int iShieldDamage);
	void GCDamageSend(CGameObject &Obj, CGameObject &ObjTarget, int AttackDamage, int MSBFlag, int MSBDamage, int iShieldDamage);
	void GCKillPlayerExpSend(CGameObject &Obj, CGameObject &ObjTarget, int exp, int AttackDamage, BOOL MSBFlag);
	void GCKillPlayerMasterExpSend(CGameObject &Obj, CGameObject &ObjTarget, int exp, int AttackDamage, BOOL MSBFlag);
	void GCDiePlayerSend(CGameObject &Obj, int TargetIndex, BYTE skill, int KillerIndex);
	void GCActionSend(CGameObject &Obj, BYTE ActionNumber, CGameObject &ObjTarget);
	void CGActionRecv(PMSG_ACTION* lpMsg, CGameObject &Obj);
	void CGMagicAttack(PMSG_MAGICATTACK* lpRecv, CGameObject &Obj);
	//void CGMagicAttack(PMSG_MAGICATTACK* lpMsg, CGameObject &Obj);
	void CGRageAttack(PMSG_RAGEATTACK_REQ* lpRecv, CGameObject &Obj);
	void CGRageAttackRange(PMSG_RAGE_ATTACK_RANGE* lpMsg, CGameObject &Obj);
	void GCMagicAttackNumberSend(CGameObject &Obj, WORD MagicNumber, CGameObject &Obj2, BYTE skillsuccess);
	void GCMonkMagicAttack(CGameObject &Obj, WORD MagicNumber, CGameObject &Obj2,  BYTE skillsuccess);
	void GCMagicCancelSend(CGameObject &Obj, WORD MagicNumber);
	void GCMagicCancel(PMSG_MAGICCANCEL* lpMsg, CGameObject &Obj);
	void GCUseEffectItem(CGameObject &Obj, int iEffectUseOption, int iOptionType, int iEffectType, int iLeftTime);
	void GCUseEffectItem2(CGameObject &Obj, int iEffectUseOption, int iOptionType, int iEffectType, int iLeftTime);
	void CGMagicCancel(PMSG_MAGICCANCEL* lpMsg, CGameObject &Obj);
	void GCUseMonsterSkillSend(CGameObject &Obj, CGameObject lpTargetObj, int iSkillNumber);
	void GCStateInfoSend(CGameObject &Obj, BYTE state, int BuffViewport);
	void CGTeleportRecv(PMSG_TELEPORT* lpMsg, CGameObject &Obj);
	void CGReqMapMove(PMSG_REQ_MAPMOVE *lpMsg, CGameObject &Obj);
	void GCSendMapMoveCheckSum(CGameObject &Obj);
	void CGTargetTeleportRecv(PMSG_TARGET_TELEPORT* lpMsg, CGameObject &Obj);
	void GCTeleportSend(CGameObject &Obj, WORD MoveNumber, BYTE MapNumber, BYTE MapX, BYTE MapY, BYTE Dir);
	void CGBeattackRecv(BYTE* lpRecv, CGameObject &Obj, int magic_send);
	void CGDurationMagicRecv(PMSG_DURATION_MAGIC_RECV * lpMsg, CGameObject &Obj);
	void CGDurationMagicRecv(LPBYTE lpRecv, CGameObject &Obj);
	void ObjectMapJoinPositionSend(CGameObject &Obj);
	void CGUseItemRecv(PMSG_USEITEM* lpMsg, CGameObject &Obj);
	void GCReFillSend(CGameObject &Obj, int Life, BYTE Ipos, BYTE flag,  WORD wShield);
	void GCManaSend(CGameObject &Obj, int Mana, BYTE Ipos, BYTE flag,  WORD BP);
	void GCInventoryItemDeleteSend(CGameObject &Obj, BYTE pos, BYTE flag);
	void GCItemObjectUseSpecialTimeSend(CGameObject &Obj, BYTE number, int time);
	void GCItemObjectDurSend(CGameObject &Obj, BYTE pos, BYTE dur, BYTE flag);
	void GCItemObjectDurSend2(CGameObject &Obj, BYTE pos, BYTE dur, BYTE flag);
	void CGWeatherSend(CGameObject &Obj, BYTE weather);
	void GCServerCmd(CGameObject &Obj, BYTE type, BYTE Cmd1, BYTE Cmd2);
	void GCReqmoveDevilSquare(PMSG_REQ_MOVEDEVILSQUARE* lpMsg, CGameObject &Obj);
	void GCReqDevilSquareRemainTime(PMSG_REQ_DEVILSQUARE_REMAINTIME* lpMsg, CGameObject &Obj);
	void AllSendMsg(BYTE* Msg, int size);
	void AllSendSameMapMsg(BYTE* Msg, int size, BYTE mapnumber);
	void GCSendPing(CGameObject &Obj);
	void GCPingSendRecv(PMSG_PING_RESULT* aRecv, CGameObject &Obj);
	void GCRegEventChipRecv(PMSG_REGEVENTCHIP* lpMsg, CGameObject &Obj);
	void GCGetMutoNumRecv(PMSG_GETMUTONUMBER* lpMsg, CGameObject &Obj);
	void GCUseEndEventChipRescv(CGameObject &Obj);
	void GCUseRenaChangeZenRecv(PMSG_EXCHANGE_EVENTCHIP* lpMsg, CGameObject &Obj);
	void CGRequestQuestInfo(CGameObject &Obj);
	void GCSendQuestInfo(CGameObject &Obj, int QuestIndex);
	void CGSetQuestState(PMSG_SETQUEST* lpMsg, CGameObject &Obj);
	void GCSendQuestPrize(CGameObject &Obj, BYTE Type, BYTE Count);
	void CGCloseWindow(CGameObject &Obj);
	void CGRequestEnterBloodCastle(PMSG_REQ_MOVEBLOODCASTLE* lpMsg, CGameObject &Obj);
	void CGRequestEnterChaosCastle(PMSG_REQ_MOVECHAOSCASTLE* lpMsg, CGameObject &Obj);
	void CGRequestRepositionUserInChaosCastle(PMSG_REQ_REPOSUSER_IN_CC* lpMsg, CGameObject &Obj);
	void CGRequestEventEnterCount(PMSG_REQ_CL_ENTERCOUNT* lpMsg, CGameObject &Obj);
	void CGRequestLottoRegister(PMSG_REQ_2ANV_LOTTO_EVENT* lpMsg, CGameObject &Obj);
	void CGReqMoveOtherServer(PMSG_REQ_MOVE_OTHERSERVER* lpMsg, CGameObject &Obj);
	void GCPacketCheckSumRecv(PMSG_PACKETCHECKSUM* aRecv, CGameObject &Obj);
	void CGDuelStartRequestRecv(PMSG_REQ_START_DUEL* lpMsg, CGameObject &Obj);
	void CGDuelEndRequestRecv(PMSG_REQ_END_DUEL* lpMsg, CGameObject &Obj);
	void CGDuelOkRequestRecv(PMSG_ANS_DUEL_OK* lpMsg, CGameObject &Obj);
	void GCSendDuelScore(CGameObject &Obj1, CGameObject &Obj2);
	void GCSendGetItemInfoForParty(CGameObject &Obj, class CMapItem* lpItem);
	void GCSendEffectInfo(CGameObject &Obj, BYTE btType);
	void CGRequestPetItemCommand(PMSG_REQUEST_PET_ITEM_COMMAND* lpMsg, CGameObject &Obj);
	void CGRequestPetItemInfo(CGameObject &Obj, PMSG_SEND_PET_ITEMINFO &data);
	void GCGuildViewportInfo(PMSG_REQ_GUILDVIEWPORT* aRecv, CGameObject &Obj);
	void CGGuildAssignStatus(PMSG_GUILD_ASSIGN_STATUS_REQ* aRecv, CGameObject &Obj);
	void CGGuildAssignType(PMSG_GUILD_ASSIGN_TYPE_REQ* aRecv, CGameObject &Obj);
	void CGRelationShipReqJoinBreakOff(PMSG_RELATIONSHIP_JOIN_BREAKOFF_REQ* aRecv, CGameObject &Obj);
	void CGRelationShipAnsJoinBreakOff(PMSG_RELATIONSHIP_JOIN_BREAKOFF_ANS* aRecv, CGameObject &Obj);
	void CGUnionList(PMSG_UNIONLIST_REQ* aRecv, CGameObject &Obj);
	void CGRelationShipReqKickOutUnionMember(PMSG_KICKOUT_UNIONMEMBER_REQ* aRecv, CGameObject &Obj);
	void CGReqMapSvrAuth(PMSG_REQ_MAPSERVERAUTH* lpMsg, CGameObject &Obj);
	void GCAnsMapSvrAuth(CGameObject &Obj, int iResult);
	void CGReqCastleSiegeState(PMSG_REQ_CASTLESIEGESTATE* lpMsg, CGameObject &Obj);
	void GCAnsCastleSiegeState(CGameObject &Obj, int iResult, char* lpszGuildName, char* lpszGuildMaster);
	void CGReqRegCastleSiege(PMSG_REQ_REGCASTLESIEGE* lpMsg, CGameObject &Obj);
	void GCAnsRegCastleSiege(CGameObject &Obj, int iResult, char* lpszGuildName);
	void CGReqGiveUpCastleSiege(PMSG_REQ_GIVEUPCASTLESIEGE* lpMsg, CGameObject &Obj);
	void GCAnsGiveUpCastleSiege(CGameObject &Obj, int iResult, int bGiveUp, int iMarkCount, char* lpszGuildName);
	void CGReqGuildRegInfo(PMSG_REQ_GUILDREGINFO* lpMsg, CGameObject &Obj);
	void GCAnsGuildRegInfo(CGameObject &Obj, int iResult,CSP_ANS_GUILDREGINFO* lpMsgResult);
	void CGReqRegGuildMark(PMSG_REQ_REGGUILDMARK* lpMsg, CGameObject &Obj);
	void GCAnsRegGuildMark(CGameObject &Obj, int iResult,CSP_ANS_GUILDREGMARK* lpMsgResult);
	void CGReqNpcBuy(PMSG_REQ_NPCBUY* lpMsg, CGameObject &Obj);
	void GCAnsNpcBuy(CGameObject &Obj, int iResult, int iNpcNumber, int iNpcIndex);
	void CGReqNpcRepair(PMSG_REQ_NPCREPAIR* lpMsg, CGameObject &Obj);
	void GCAnsNpcRepair(CGameObject &Obj, int iResult, int iNpcNumber, int iNpcIndex, int iNpcHP, int iNpcMaxHP);
	void CGReqNpcUpgrade(PMSG_REQ_NPCUPGRADE* lpMsg, CGameObject &Obj);
	void GCAnsNpcUpgrade(CGameObject &Obj, int iResult, int iNpcNumber, int iNpcIndex, int iNpcUpType, int iNpcUpValue);
	void CGReqTaxMoneyInfo(PMSG_REQ_TAXMONEYINFO* lpMsg, CGameObject &Obj);
	void GCAnsTaxMoneyInfo(CGameObject &Obj, int iResult, BYTE btTaxRateChaos, BYTE btTaxRateStore, __int64 i64Money);
	void CGReqTaxRateChange(PMSG_REQ_TAXRATECHANGE* lpMsg, CGameObject &Obj);
	void GCAnsTaxRateChange(CGameObject &Obj, int iResult, BYTE btTaxType, int iTaxRate);
	void CGReqMoneyDrawOut(PMSG_REQ_MONEYDRAWOUT* lpMsg, CGameObject &Obj);
	void GCAnsMoneyDrawOut(CGameObject &Obj, int iResult, __int64 i64Money);
	void GCAnsCsGateState(CGameObject &Obj, int iResult, int iGateIndex);
	void CGReqCsGateOperate(PMSG_REQ_CSGATEOPERATE* lpMsg, CGameObject &Obj);
	void GCAnsCsGateOperate(CGameObject &Obj, int iResult, int iGateIndex, int iGateOperate);
	void GCAnsCsGateCurState(CGameObject &Obj, int iGateIndex, int iGateOperate);
	void GCAnsCsAccessSwitchState(CGameObject &Obj, int iSwitchIndex, int iSwitchUserIndex, BYTE btSwitchState);
	void GCAnsCsAccessCrownState(CGameObject &Obj, BYTE btCrownState);
	void GCAnsCsNotifyStart(CGameObject &Obj, BYTE btStartState);
	void GCAnsCsNotifyProgress(CGameObject &Obj, BYTE btCastleSiegeState, LPCSTR lpszGuildName);
	void GCAnsCsMapSvrTaxInfo(CGameObject &Obj, BYTE btTaxType, BYTE btTaxRate);
	void CGReqCsMiniMapData(PMSG_REQ_MINIMAPDATA* lpMsg, CGameObject &Obj);
	void GCAnsCsMiniMapData(CGameObject &Obj, BYTE btResult);
	void CGReqStopCsMiniMapData(PMSG_REQ_STOPMINIMAPDATA* lpMsg, CGameObject &Obj);
	void CGReqCsSendCommand(PMSG_REQ_CSCOMMAND* lpMsg, CGameObject &Obj);
	void GCAnsCsSendCommand(int iCsJoinSide, BYTE btTeam, BYTE btX, BYTE btY, BYTE btCommand);
	void GCAnsCsLeftTimeAlarm(BYTE btHour, BYTE btMinute);
	void GCAnsSelfCsLeftTimeAlarm(CGameObject &Obj, BYTE btHour, BYTE btMinute);
	void CGReqCsSetEnterHuntZone(PMSG_REQ_CSHUNTZONEENTER* lpMsg, CGameObject &Obj);
	void GCAnsCsSetEnterHuntZone(CGameObject &Obj, BYTE btResult, BYTE btEnterHuntZone);
	void CGReqNpcDbList(PMSG_REQ_NPCDBLIST* lpMsg, CGameObject &Obj);
	void CGReqCsRegGuildList(PMSG_REQ_CSREGGUILDLIST* lpMsg, CGameObject &Obj);
	void CGReqCsAttkGuildList(PMSG_REQ_CSATTKGUILDLIST* lpMsg, CGameObject &Obj);
	void CGReqWeaponUse(PMSG_REQ_USEWEAPON* aRecv, CGameObject &Obj);
	void CGReqWeaponDamageValue(PMSG_REQ_WEAPON_DAMAGE_VALUE* aRecv, CGameObject &Obj);
	void CGReqGuildMarkOfCastleOwner(PMSG_REQ_GUILDMARK_OF_CASTLEOWNER* aRecv, CGameObject &Obj);
	void CGReqJewelMix(PMSG_REQ_JEWEL_MIX* lpMsg, CGameObject &Obj);
	void GCAnsJewelMix(CGameObject &Obj, int iResult);
	void CGReqJewelUnMix(PMSG_REQ_JEWEL_UNMIX* lpMsg, CGameObject &Obj);
	void GCAnsJewelUnMix(CGameObject &Obj, int iResult);
	void CGReqCrywolfInfo(PMSG_REQ_CRYWOLF_INFO* lpMsg, CGameObject &Obj);
	void GCAnsCrywolfInfo(CGameObject &Obj, BYTE btOccupationState, BYTE btCrywolfState);
	void CGReqAlatrContract(PMSG_REQ_CRYWOLF_ALTAR_CONTRACT* lpMsg, CGameObject &Obj);
	void CGReqPlusChaosRate(PMSG_REQ_CRYWOLF_BENEFIT_PLUS_CHAOSRATE* lpMsg, CGameObject &Obj);
	void CGReqKanturuStateInfo(PMSG_REQ_KANTURU_STATE_INFO* lpMsg, CGameObject &Obj);
	void GCReqEnterKanturuBossMap(PMSG_REQ_ENTER_KANTURU_BOSS_MAP* lpMsg, CGameObject &Obj);
	void GCIllusionTempleSendReward(CGameObject &Obj);
	void WereWolfQuarrelCheck(CGameObject &Obj);
	void GateKeeperCheck(CGameObject &Obj);
	void GCMasterLevelUpMsgSend(CGameObject &Obj);
	void CGReqIllusionTempleUseSkill(PMSG_REQ_USEILLUSIONTEMPLESKILL * aRecv, CGameObject &Obj);
	void GCSendIllusionTempleKillPoint(CGameObject &Obj, BYTE KillPoint);
	void CGReqLuckyCoinRegister(PMSG_REQ_LUCKYCOIN_REGISTER * aRecv, CGameObject &Obj);
	void CGReqLuckyCoinInfo(CGameObject &Obj);
	void CGReqLuckyCoinTrade(PMSG_REQ_LUCKYCOIN_TRADE * aRecv, CGameObject &Obj);
	void GCAnsLuckyCoinTrade(CGameObject &Obj, BYTE Result);
	void CGReqCastleHuntZoneEntrance(PMSG_REQ_MOVE_TO_CASTLE_HUNTZONE* aRecv, CGameObject &Obj);
	void GCSendObjectCreationState(int iObjectIndex);
	void GCSendObjectHP(CGameObject &Obj, int aTargetIndex);
	void CGReqAntiCheatRecv(CGameObject &Obj, PMSG_SEND_AH_INFO * aRecv);
	void CGReqFileCrcRecv(CGameObject &Obj, PMSG_REQ_CRCDATA * aRecv);
	void GCElementalDamageSend(CGameObject &Obj, int TargetIndex, int Damage, int Elemental);
	void GCSendErtelInfo(CGameObject &Obj);
	void CGReqEnterAcheron(CGameObject &Obj);
	void GCObjectLifeInfo(CGameObject &Obj, int sObjNum, int iMaxLife, int iCurLife);
	void CGAgilityRecv(CGameObject &Obj, PMSG_AGILITYSEND * aRecv);
	void GCPriceSend(CGameObject &Obj, BYTE type, SHOP_DATA *lpShopData);
	int OnCGInviteDuel(PMSG_REQ_DUEL_INVITE* lpMsg, CGameObject &Obj);
	int OnCGAnswerDuel(PMSG_ANS_DUEL_ANSWER* lpMsg, CGameObject &Obj);
	int OnCGLeaveDuel(PMSG_REQ_DUEL_EXIT* lpMsg, CGameObject &Obj);
	int OnDuelChannelJoin(PMSG_REQ_DUEL_JOINCNANNEL* lpMsg, CGameObject &Obj);
	int OnDuelChannelLeave(PMSG_REQ_DUEL_LEAVECNANNEL* lpMsg, CGameObject &Obj);
	void CGReqRegGensMember(PMSG_REQ_REG_GENS_MEMBER *lpMsg, CGameObject &Obj);
	void CGReqSecedeGensMember(PMSG_REQ_SEGEDE_GENS_MEMBER *lpMsg, CGameObject &Obj);
	void CGReqGensReward(PMSG_GENS_REWARD_CODE *lpMsg, CGameObject &Obj);
	void CGReqGensMemberInfo(PMSG_REQ_GENS_INFO *lpMsg, CGameObject &Obj);
	void CGInventoryEquipment(PMSG_REQ_INVENTORY_EQUIPMENT_ITEM *lpMsg, CGameObject &Obj);
	void CGReqUseTransformationRing(PMSG_REQ_USETRANSFORMATIONRING *lpMsg, CGameObject &Obj);
	void GCSendAttackSpeed(CGameObject &Obj);
	void GCChaosMachinePriceSend(CGameObject &Obj);
	void CGReqEnterDoppelGanger(PMSG_REQ_ENTER_DOPPELGANGER *lpMsg, CGameObject &Obj);
	void CGReqEnterZone(PMSG_REQ_ENTER_ZONE *lpMsg, CGameObject &Obj);	
	void CGReqInJewelPentagramItem(PMSG_REQ_IN_PENTAGRAM_JEWEL *lpMsg, CGameObject &Obj);
	void GCAnsInJewelPentagramItem(CGameObject &Obj, int iResult, BYTE btJewelPos, BYTE btJewelIndex, BYTE btItemType, WORD wItemIndex, BYTE btMainAttribute, BYTE btLevel, BYTE btRank1OptionNum, BYTE btRank1Level, BYTE btRank2OptionNum, BYTE btRank2Level, BYTE btRank3OptionNum, BYTE btRank3Level, BYTE btRank4OptionNum, BYTE btRank4Level, BYTE btRank5OptionNum, BYTE btRank5Level);
	void CGReqOutJewelPentagramItem(PMSG_REQ_OUT_PENTAGRAM_JEWEL *lpMsg, CGameObject &Obj);
	void GCAnsOutJewelPentagramItem(CGameObject &Obj, int iResult, BYTE btJewelPos, BYTE btJewelDBIndex);
	void CGReqRefinePentagramJewel(PMSG_REQ_REFINE_PENTAGRAM_JEWEL *lpMsg, CGameObject &Obj);
	void GCAnsRefinePentagramJewel(CGameObject &Obj, BYTE btResult);
	void CGReqUpgradePentagramJewel(PMSG_REQ_UPGRADE_PENTAGRAM_JEWEL *lpMsg, CGameObject &Obj);
	void GCAnsUpgradePentagramJewel(CGameObject &Obj, BYTE btResult);
	void GCAnsPentagramJewelInOut(CGameObject &Obj, BYTE btResult);
	void CGReqArcaBattleGuildMasterJoin(PMSG_REQ_ARCA_BATTLE_JOIN *lpMsg, CGameObject &Obj);
	void CGReqArcaBattleGuildMemberJoin(PMSG_REQ_ARCA_BATTLE_JOIN *lpMsg, CGameObject &Obj);
	void CGReqArcaBattleEnter(PMSG_REQ_ARCA_BATTLE_ENTER *lpMsg, CGameObject &Obj);
	void CGReqAcheronEnter(PMSG_REQ_ACHERON_ENTER *lpMsg, CGameObject &Obj);
	void CGReqArcaBattleBootyExchange(CGameObject &Obj);
	void CGReqSpritemapExchange(CGameObject &Obj);
	void CGReqRegisteredMemberCnt(CGameObject &Obj);
	void GCSendRecvCheck(CGameObject &Obj);
	void CGReqAntihackBreach(CGameObject &Obj, PMSG_ANTIHACK_BREACH *lpMsg);
	void CGReqAntihackCheck(CGameObject &Obj, PMSG_ANTIHACK_CHECK *lpMsg);
	void GCMuunItemDurSend(CGameObject &Obj, BYTE pos, BYTE dur);
	void GCMuunEquipmentChange(CGameObject &Obj, int pos);
	void GCMuunInventoryItemDeleteSend(CGameObject &Obj, BYTE pos, BYTE flag);
	void GCMuunInventoryItemOneSend(CGameObject &Obj, int pos); 
	void CGMuunItemGetRequest(PMSG_MUUNITEM_GETREQUEST *lpMsg, CGameObject &Obj);
	void CGMuunItemSellRequestRecv(PMSG_MUUN_ITEM_SELLREQUEST *lpMsg, CGameObject &Obj);
	void CGReqGuildMatchingList(PMSG_REQ_GUILDMATCHINGLIST *lpMsg, int nUserIndex);
	void CGReqGuildMatchingListSearchWord(PMSG_REQ_GUILDMATCHINGLISTSEARCHWORD *lpMsg, int nUserIndex);
	void CGReqRegGuildMatchingList(PMSG_REQ_REGGUILDMATCHINGDATA *lpMsg, int nUserIndex);
	void CGReqCancelGuildMatchingList(PMSG_REQ_CANCEL_GUILDMATCHINGLIST *lpMsg, int nUserIndex);
	void CGReqJoinGuildMatching(PMSG_REQ_JOIN_GUILDMATCHING *lpMsg, int nUserIndex);
	void CGReqCancelJoinGuildMatching(int nUserIndex);
	void CGReqAllowJoinGuildMatching(PMSG_REQ_ALLOW_JOIN_GUILDMATCHING *lpMsg, int nUserIndex);
	void CGReqGetAllowListJoinGuildMatching(PMSG_REQ_ALLOWLIST_GUILDMATCHING *lpMsg, int nUserIndex);
	void CGReqGetWaitStateListGuildMatching(int nUserIndex);

	void CGReqRegWantedPartyMember(PMSG_REQ_REG_WANTED_PARTYMEMBER *lpMsg, int nUserIndex);
	void CGReqGetPartyMatchingList(PMSG_REQ_GET_PARTYMATCHINGLIST *lpMsg, int nUserIndex);
	void CGReqJoinMemberPartyMatching(PMSG_REQ_MEMBERJOIN_PARTYMATCHINGLIST *lpMsg, int nUserIndex);
	void CGReqMemberJoinStateList(PMSG_REQ_MEMBERJOIN_STATELIST_PARTYMATCHING *lpMsg, int nUserIndex);
	void CGReqMemberJoinStateListLeader(PMSG_REQ_WAITLIST_PARTYMATCHING *lpMsg, int nUserIndex);
	void CGReqAcceptJoinMemberPartyMatching(PMSG_REQ_ACCEPTMEMBER_PARTYMATCHING *lpMsg, int nUserIndex);
	void CGReqCancelPartyMatching(PMSG_REQ_CANCEL_JOIN_PARTYMATCHING *lpMsg, int nUserIndex);

	void GCDisplayBuffeffectPartyMember(CGameObject &Obj);
	void GCPartyMemberPosition(int nIndex);
	void CGReqSendMemberPosInfoStart(int nIndex);
	void CGReqSendMemberPosInfoStop(int nIndex);
	void GCReqSendNpcPosInfo(PMSG_REQ_NPC_POSITION *lpMsg, int nIndex);

	void CGReqCCF_DayTime(CGameObject &Obj);
	void CGReqCCF_EnterCheck(CGameObject &Obj);
	void CG_CCF_UI_OnOff(PMSG_CCF_UI_ONOFF *lpMsg, int nUserIndex);
	int	 CGReqEnterChaosCastleFinal(CGameObject &Obj);
	void CGRequestRepositionUserInCCF(PMSG_REQ_REPOSUSER_IN_CCF *lpMsg, CGameObject &Obj);
	void CGReq_CCF_Ranking(PMSG_REQ_CCF_RANKING *lpMsg, CGameObject &Obj);

	void CGReqEventInvenOpen(LPBYTE lpRecv, CGameObject &Obj);
	void CGEventItemGetRequest(PMSG_EVENTITEM_GETREQUEST *lpMsg, CGameObject &Obj);
	bool CGEventItemDropRequest(PMSG_EVENTITEM_THROW *lpMsg, CGameObject &Obj);
	void GCEventInventoryItemListSend(CGameObject &Obj);
	void GCEventItemDurSend(CGameObject &Obj, BYTE pos, BYTE dur);
	void GCEventInvenItemOneSend(CGameObject &Obj, int pos);
	void GCEventInventoryItemDeleteSend(CGameObject &Obj, BYTE pos, BYTE flag);

	void GCResSendExpEventInfo(CGameObject &Obj);

	void CGReq_ITL_Relics(PMSG_REQ_ITL_RELATE_RELICS *lpMsg, CGameObject &Obj);
	void CG_Req_Enter_ITR(PMSG_REQ_ENTER_ITR *lpMsg, CGameObject &Obj);
	void CG_ReqAcceptEnterITR(PMSG_REQ_ACCEPTENTER_ITR *lpMsg, CGameObject &Obj);
	BYTE EnterITRCheckUser(CGameObject &Obj, int &TroubleUserIndex);

	void CGReqUBFMyCharacterInfo(PMSG_REQ_UBF_INFO *lpMsg, CGameObject &Obj);
	void CGReqUBFJoin(PMSG_REQ_UBF_JOIN *lpMsg, CGameObject &Obj);
	void CGReqUBFCancel(PMSG_REQ_UBF_CANCEL *lpMsg, CGameObject &Obj);
	void CGReqUBFGetRealName(PMSG_REQ_UBF_REAL_NAME *lpMsg, CGameObject &Obj);
	void CGReqUBFGetReward(PMSG_REQ_GET_REWARD *lpMsg, CGameObject &Obj);

	void CGReqDSFSchedule(CGameObject &Obj);
	void CGReqDSFEnter(CGameObject &Obj);
	int EnterDSFCheckUser(CGameObject &Obj, int & TroubleUserIndex);
	void CGReqAcceptEnterDSF(PMSG_REQ_DSF_ACCEPTENTER *lpMsg, CGameObject &Obj);
	void CGReqDSFGoFinalParty(PMSG_REQ_DSF_GO_FINAL_PARTY_INFO *lpMsg, CGameObject &Obj);
	void CGReqDSFGetReward(PMSG_REQ_DSF_GET_REWARD *lpMsg, CGameObject &Obj);

	void CGReqDoUsePopupType(CGameObject &Obj);
	void GCSendEventBanner(CGameObject &Obj, int iBannerType);

	void GCSendRareItemPriceInfo(CGameObject &Obj);
	void GCSendDisableReconnect(CGameObject &Obj);
	bool PacketCheckTime(CGameObject &Obj);
	void GCSendDisableReconnectSystem(CGameObject &Obj);
	void GCAlterPShopVault(CGameObject &Obj, BYTE type);
	void GCSetCharColors(CGameObject &Obj);

	void GCSendRuud(CGameObject &Obj, int iRuud, int iObtainedRuud, bool bIsObtainedRuud);
	void CGReqUseBoxInInventory(CGameObject &Obj, PMSG_REQ_USE_BOX * aRecv);

	void CGEventEntryNotice(int EventType, BYTE state); // event entry notify
	void CGReqNixieBossEnter(PMSG_REQ_NIXIELAKE_ENTER *lpMsg, CGameObject &Obj);
	void CGReqHuntingLog(CGameObject &Obj);

	void GCPlayerStatsPanelRates(CGameObject &Obj);
	void GCPlayerStatsPanelNew(CGameObject &Obj);

	void CGRequestStartMuBot(PMSG_MUBOT_REQ_START* lpMsg, CGameObject &Obj);
	void CGSaveMuBotSettings(PMSG_MUBOT_SETTINGS_RECV* lpMsg, CGameObject &Obj);
	void GCSendMuBotSettings(CGameObject &Obj, BYTE* lpData);

	void CGRecvHitHackValues(CGameObject &Obj, PMSG_SEND_HITHACK_INFO * lpMsg);

	void gObjRequestPetItemInfo(CGameObject &Obj, int inventype);
	std::vector<Recv_PetItem_Info> gObjRequestPetItemInfoDS(CGameObject &Obj, int inventype, std::vector<int> serials);


	// From SProtocol.
	void GJPUserClose(LPSTR szAccountID);
	void GJPUserClose(CGameObject &Obj);


	bool First = true;

	CQuery* m_CharDB;
	CQuery* m_AccDB;
	CQuery* m_GSDB;
	CQuery* m_PetDB;
	CQuery* m_CastleDB;
	CQuery* m_CrywolfDB;
	CQuery* m_PentagramDB;
	CQuery* m_EventDB;
	CQuery* m_RankingDB;
	CQuery* m_ItemShopDB;
	CQuery* m_PeriodItemDB;
	CQuery* m_CharMiscDB;
	CQuery* m_ArcaDB;
	CQuery* m_QuestExpDB;
	CQuery* m_LuckyItemDB;
	CQuery* m_CCFinalDB;
	CQuery* m_RummyDB;
	CQuery* m_MineDB;
	CQuery* m_PShopDB;
	CQuery* m_EventInvDB;
	CQuery* m_MuunDB;
	CQuery* m_OptionDataDB;
	CQuery* m_ReBuyDB;
	CQuery* m_GremoryCaseDB;
	CQuery* m_BattleCoreDB;
	CQuery* m_DSFinalDB;
	CQuery* m_EvoMonDB;
	CQuery* m_Survivor;

private:
	bool DataEncryptCheck(CGameObject &Obj, BYTE protoNum, BOOL Encrypt);
};

extern GameProtocol gGameProtocol;

////////////////////////////////////////////// DS PROTOCOL /////////////////////


void DataServerProtocolCore(BYTE protoNum, LPBYTE aRecv, int aLen);
void DataServerLogin();
void DataServerLoginResult(SDHP_RESULT* lpMsg);
void JGPGetCharList(LPBYTE lpRecv);
void DataServerGetCharListRequest(short aIndex);
void JGCharacterCreateRequest(SDHP_CREATECHARRESULT* lpMsg);
void JGCharacterCreateFailSend(CGameObject &Obj, char* id);
void JGCharDelRequest(SDHP_CHARDELETERESULT* lpMsg);
void JGGetCharacterInfo(SDHP_DBCHAR_INFORESULT* lpMsg);
void GCItemObjectListSend(CGameObject &Obj);
void GJSetCharacterInfo(struct OBJECTSTRUCT* lpObj, CGameObject &Obj, BOOL bMapServerMove);
void GDGetWarehouseList(CGameObject &Obj, char* AccountID);
void DGGetWarehouseList(SDHP_GETWAREHOUSEDB_SAVE* lpMsg);
void GDGetWarehouseNoItem(SDHP_GETWAREHOUSEDB_RESULT* lpMsg);
void GDSetWarehouseList(CGameObject &Obj, BOOL bCloseWindow);
void DGSetWarehouseList(PMSG_ANS_WARESAVE* lpMsg);
void GDUserItemSave(OBJECTSTRUCT* lpObj);
void GDSetWarehouseMoney(CGameObject &Obj);
void GDGameServerInfoSave();
void ItemCreate(CGameObject &Obj, BYTE MapNumber, BYTE x, BYTE y, int type, BYTE level, BYTE dur, BYTE Op1, BYTE Op2, BYTE Op3, int LootIndex, BYTE NewOption, BYTE SetOption, time_t lDuration, BYTE *SocketOption, BYTE MainAttribute);
void PetGameProtocol.ItemSerialCreateSend(CGameObject &Obj, BYTE MapNumber, BYTE x, BYTE y, int type, BYTE level, BYTE dur, BYTE Op1, BYTE Op2, BYTE Op3, int LootIndex, BYTE NewOption, BYTE SetOption);
void ExpGameProtocol.ItemSerialCreateSend(CGameObject &Obj, BYTE MapNumber, BYTE x, BYTE y, int type, BYTE level, BYTE dur, BYTE Op1, BYTE Op2, BYTE Op3, int LootIndex, BYTE NewOption, BYTE SetOption, time_t ExpTime);
void ItemSerialCreateRecv(SDHP_ITEMCREATERECV* lpMsg);
void ItemMovePathSave(char* ActID, char* Name, BYTE level, BYTE mapnumber, BYTE x, BYTE y, char* Item, BYTE op1, BYTE op2, BYTE op3, DWORD serial);
void DGOptionDataSend(CGameObject &Obj, char* szName, LPBYTE KeyBuffer, BYTE GO, BYTE Qk, BYTE Wk, BYTE Ek, BYTE ChatWnd, BYTE Rk, int QWER, BYTE Transform);
void DGOptionDataRecv(SDHP_SKILLKEYDATA_SEND* lpMsg);
void DGDeleteTempUserInfo(SDHP_DELETE_TEMPUSERINFO_RESULT * aRecv);
void DGMoveOtherServer(SDHP_CHARACTER_TRANSFER_RESULT* lpMsg);
void gObjRequestPetItemInfo(CGameObject &Obj, int inventype);
void DGRecvPetItemInfo(LPBYTE lpData);
void gObjSavePetItemInfo(CGameObject &Obj, int inventype);
void GS_GDReqCastleTotalInfo(int iMapSvrGroup, int iCastleEventCycle);
void GS_GDReqOwnerGuildMaster(int iMapSvrGroup, CGameObject &Obj);
void GS_GDReqCastleNpcBuy(int iMapSvrGroup, CGameObject &Obj, int iNpcNumber, int iNpcIndex, int iNpcDfLevel, int iNpcRgLevel, int iNpcMaxHP, int iNpcHP, BYTE btNpcX, BYTE btNpcY, BYTE btNpcDIR, int iBuyCost);
void GS_GDReqCastleNpcRepair(int iMapSvrGroup, CGameObject &Obj, int iNpcNumber, int iNpcIndex, int iRepairCost);
void GS_GDReqCastleNpcUpgrade(int iMapSvrGroup, CGameObject &Obj, int iNpcNumber, int iNpcIndex, int iNpcUpType, int iNpcUpValue, int iNpcUpIndex);
void GS_GDReqTaxInfo(int iMapSvrGroup, CGameObject &Obj);
void GS_GDReqTaxRateChange(int iMapSvrGroup, CGameObject &Obj, int iTaxType, int iTaxRate);
void GS_GDReqCastleMoneyChange(int iMapSvrGroup, CGameObject &Obj, int iMoneyChange);
//void GS_GDReqCastleDateChange(int iMapSvrGroup, CGameObject &Obj,WORD wStartYear, BYTE btStartMonth, BYTE btStartDay, WORD wEndYear, BYTE btEndMonth, BYTE btEndDay);
void GS_GDReqSiegeDateChange(int iMapSvrGroup, CGameObject &Obj, WORD wStartYear, BYTE btStartMonth, BYTE btStartDay, WORD wEndYear, BYTE btEndMonth, BYTE btEndDay);
void GS_GDReqGuildMarkRegInfo(int iMapSvrGroup, CGameObject &Obj);
void GS_GDReqSiegeEndedChange(int iMapSvrGroup, int bIsSiegeEnded);
void GS_GDReqCastleOwnerChange(int iMapSvrGroup, int bIsCastleOccupied, char* lpszGuildName);
void GS_GDReqRegAttackGuild(int iMapSvrGroup, CGameObject &Obj);
void GS_GDReqRestartCastleState(int iMapSvrGroup);
void GS_GDReqMapSvrMsgMultiCast(int iMapSvrGroup, char* lpszMsgText);
void GS_GDReqGlobalPostMultiCast(int iMapSvrGroup, CGameObject &Obj, char * szMessage);
void GS_GDReqRegGuildMark(int iMapSvrGroup, CGameObject &Obj, int iItemPos);
void GS_GDReqGuildMarkReset(int iMapSvrGroup, CGameObject &Obj, char* lpszGuildName);
void GS_GDReqGuildSetGiveUp(int iMapSvrGroup, CGameObject &Obj, int bIsGiveUp);
void GS_GDReqNpcRemove(int iMapSvrGroup, int iNpcNumber, int iNpcIndex);
void GS_GDReqCastleStateSync(int iMapSvrGroup, int iCastleState, int iTaxRateChaos, int iTaxRateStore, int iTaxHuntZone, char* lpszOwnerGuild);
void GS_GDReqCastleTributeMoney(int iMapSvrGroup, int iCastleTributeMoney);
void GS_GDReqResetCastleTaxInfo(int iMapSvrGroup);
void GS_GDReqResetSiegeGuildInfo(int iMapSvrGroup);
void GS_GDReqResetRegSiegeInfo(int iMapSvrGroup);
void GS_GDReqCastleInitData(int iMapSvrGroup, int iCastleEventCycle);
void GS_GDReqCastleNpcInfo(int iMapSvrGroup, CGameObject &Obj);
void GS_GDReqAllGuildMarkRegInfo(int iMapSvrGroup, CGameObject &Obj);
void GS_GDReqCalcRegGuildList(int iMapSvrGroup);
void GS_GDReqCsLoadTotalGuildInfo(int iMapSvrGroup);
void GS_DGAnsCastleTotalInfo(LPBYTE lpRecv);
void GS_DGAnsOwnerGuildMaster(LPBYTE lpRecv);
void GS_DGAnsCastleNpcBuy(LPBYTE lpRecv);
void GS_DGAnsCastleNpcRepair(LPBYTE lpRecv);
void GS_DGAnsCastleNpcUpgrade(LPBYTE lpRecv);
void GS_DGAnsTaxInfo(LPBYTE lpRecv);
void GS_DGAnsTaxRateChange(LPBYTE lpRecv);
void GS_DGAnsCastleMoneyChange(LPBYTE lpRecv);
void GS_DGAnsSiegeDateChange(LPBYTE lpRecv);
void GS_DGAnsGuildMarkRegInfo(LPBYTE lpRecv);
void GS_DGAnsSiegeEndedChange(LPBYTE lpRecv);
void GS_DGAnsCastleOwnerChange(LPBYTE lpRecv);
void GS_DGAnsRegAttackGuild(LPBYTE lpRecv);
void GS_DGAnsRestartCastleState(LPBYTE lpRecv);
void GS_DGAnsMapSvrMsgMultiCast(LPBYTE lpRecv);
void GS_DGAnsGlobalPostMultiCast(LPBYTE lpRecv);
void GS_DGAnsRegGuildMark(LPBYTE lpRecv);
void GS_DGAnsGuildMarkReset(LPBYTE lpRecv);
void GS_DGAnsGuildSetGiveUp(LPBYTE lpRecv);
void GS_DGAnsNpcRemove(LPBYTE lpRecv);
void GS_DGAnsCastleStateSync(LPBYTE lpRecv);
void GS_DGAnsCastleTributeMoney(LPBYTE lpRecv);
void GS_DGAnsResetCastleTaxInfo(LPBYTE lpRecv);
void GS_DGAnsResetSiegeGuildInfo(LPBYTE lpRecv);
void GS_DGAnsResetRegSiegeInfo(LPBYTE lpRecv);
void GS_DGAnsCastleInitData(LPBYTE lpRecv);
void GS_DGAnsCastleNpcInfo(LPBYTE lpRecv);
void GS_DGAnsAllGuildMarkRegInfo(LPBYTE lpRecv);
void GS_DGAnsFirstCreateNPC(LPBYTE lpRecv);
void GS_DGAnsCalcREgGuildList(LPBYTE lpRecv);
void GS_DGAnsCsGulidUnionInfo(LPBYTE lpRecv);
void GS_DGAnsCsSaveTotalGuildInfo(LPBYTE lpRecv);
void GS_DGAnsCsLoadTotalGuildInfo(LPBYTE lpRecv);
void GS_DGAnsCastleNpcUpdate(LPBYTE lpRecv);
void GDReqCrywolfSync(int iMapSvrGroup, int iCrywolfState, int iOccupationState);
void DGAnsCrywolfSync(LPBYTE lpRecv);
void GDReqCrywolfInfoLoad(int iMapSvrGroup);
void DGAnsCrywolfInfoLoad(LPBYTE lpRecv);
void GDReqCrywolfInfoSave(int iMapSvrGroup, int iCrywolfState, int iOccupationState);
void DGAnsCrywolfInfoSave(LPBYTE lpRecv);
void GDReqGensJoin(CGameObject &Obj, int GensID);
void DGAnsGensJoin(GSP_ANS_GENS_JOIN *lpMsg);
void GDReqGensInfo(CGameObject &Obj);
void DGAnsGensInfo(GSP_ANS_GENS_INFO *lpMsg);
void GDReqGensQuit(CGameObject &Obj);
void DGAnsGensQuit(GSP_ANS_GENS_QUIT *lpMsg);
void GDReqGensRank(CGameObject &Obj);
void DGAnsGensRank(GSP_ANS_GENS_RANK *lpMsg);
void GDReqGensSave(CGameObject &Obj);

void GDReqInGameShopItemList(CGameObject &Obj, BYTE InventoryType, BYTE InventoryNum);
void DGAnsInGameShopItemList(LPBYTE lpRecv);
void GDReqInGameShopPoint(CGameObject &Obj);
void DGAnsInGameShopPoint(ISHOP_ANS_POINT *lpMsg);
void GDReqInGameShopPointAdd(CGameObject &Obj, BYTE Type, float Coin);
void GDReqInGameShopItemBuy(CGameObject &Obj, int ID1, int ID2, int ID3, int Price, BYTE CoinType);
void DGAnsInGameShopItemBuy(LPBYTE lpRecv);
void GDReqInGameShopItemGift(CGameObject &Obj, int ID1, int ID2, int ID3, int Price, BYTE CoinType, char Target[11], char Message[200]);
void DGAnsInGameShopItemGift(LPBYTE lpRecv);
void GDReqInGameShopItemUse(CGameObject &Obj, int UniqueCode, int AuthCode);
void DGAnsInGameShopItemUse(ISHOP_ITEM_USEANS *lpMsg);
void GDReqInGameShopItemDelete(CGameObject &Obj, int UniqueCode, int AuthCode);
void GDReqInGameShopItemRollbackUse(CGameObject &Obj, int UniqueCode, int AuthCode);

void GDReqBanUser(CGameObject &Obj, BYTE Type, BYTE Ban);
void GDSetExpWare(CGameObject &Obj, BYTE ExpansionType, BYTE ExpansionLevel);
void GDCharCardBuy(char AccountID[11], BYTE Type);
void GDReqSecLock(CGameObject &Obj, int Code);
void ReqMonsterCountAns(DS_GET_MONSTERCNT * aRecv);
void ReqMonsterCount(short aIndex);
void ReqSaveMonsterCount(short aIndex, int monsterid);
void ReqSavePlayerKiller(short kIndex, short vIndex);

void GDReqArcaBattleGuildJoin(OBJECTSTRUCT *obj);
void DGAnsArcaBattleGuildJoin(PMSG_ANS_ARCA_BATTLE_GUILD_JOIN_DS *lpMsg);

void DGAnsArcaBattleGuildJoinSelect(PMSG_ANS_ARCA_BATTLE_GUILD_JOIN_DS *lpMsg);

void GDReqArcaBattleGuildMemberJoin(OBJECTSTRUCT *obj);
void DGAnsArcaBattleGuildMemberJoin(PMSG_ANS_ARCA_BATTLE_GUILD_MEMBER_JOIN_DS *lpMsg);

void GDReqArcaBattleEnter(OBJECTSTRUCT *obj, BYTE btEnterSeq);
void DGAnsArcaBattleEnter(PMSG_ANS_ARCA_BATTLE_ENTER_DS *lpMsg);

void DGAnsArcaBattleWinGuildInfo(PMSG_ANS_AB_WIN_GUILD_INFO_DS *lpMsg);

void DGReqArcaBattleProcMultiCast(PMSG_ANS_AB_PROC_STATE_DS *lpMsg);

void GDAnsJoinMemberUnder(PMSG_ANS_AB_JOIN_MEMBER_UNDER_DS *lpMsg);

void DGAns_ChaosCastle_KillPoint_Result(SDHP_ANS_KILLPOINT_RESULT_CC_UBF *lpMsg);
void DGAns_CCF_Info_Notify(SDHP_ANS_CCF_INFO_NOTIFY *lpMsg);
void DGAns_GetCCFPermission(SDHP_ANS_CCF_GETPERMISSION *lpMsg);

void GCMuunInventoryItemListSend(CGameObject &Obj);

void GDReqSaveEventInvenItem(OBJECTSTRUCT *lpObj);
void GDReqLoadEventInvenItem(OBJECTSTRUCT *lpObj);
void DGLoadEventInvenItem(SDHP_ANS_DBEVENT_INVEN_LOAD *lpMsg);

void GDReqSwitchWare(CGameObject &Obj, int WareID);
void DGAnsSwitchWare(PMSG_ANS_SWITCHWARE *lpMsg);

void DGAnsUBFAccountUserInfo(PMSG_ANS_UBF_ACCOUNT_USERINFO *lpMsg);
void DGUBFRegisterAccountUserResult(PMSG_UBF_REGISTER_ACCOUNT_USER_RESULT *lpMsg);
void DGUBFAccountUserCopyResult(PMSG_UBF_ACCOUNT_USER_COPY_RESULT *lpMsg);
void DGAnsUBFGetReward(PMSG_ANS_UBF_GET_REWARD *lpMsg);
void DGAnsSetReceivedWinnerItem(PMSG_ANS_UBF_SET_RECEIVED_REWARD *lpMsg);
void DGUBFAnsCancelToJoinResult(PMSG_UBF_ANS_CANCEL_REGISTER_USER *lpMsg);
void DGUBFAnsGetRealNameAndServerCode(PMSG_ANS_GET_UBF_REAL_NAME *lpMsg);
void GDReqCopyPetItemInfo(CGameObject &Obj);

void GDReqDSFCanPartyEnter(CGameObject &Obj);
void DG_DSF_CanPartyEnter(PMSG_ANS_DSF_CAN_PARTY_ENTER *lpMsg);
void DG_DSF_PartyRankRenew(PMSG_ANS_DSF_PARTYRANKRENEW *lpMsg);
void DG_DSF_GoFinalParty(LPBYTE lpRecv);
void DG_DSF_GetReward(PMSG_ANS_GET_DSF_REWARD *lpMsg);
void DGReqOtherChannelWishper(PMSG_RECV_CHATDATA_WHISPER *lpMsg);
void GDReqMapSrvGroupServerCount();
void DGWhisperResponseRecv(DSMSG_GS_WHISPER_RESULT * aRecv);
void GDWhisperResultSend(BYTE Result, int OriginPlayerIndex, int OriginGS);
void GDDisconnectOtherChannel(PMSG_RECV_DC_OTHER_CHANNEL * aRecv);
void GDReqDisconnectOtherChannel(char * charname);
void DGDisconnectOtherChannel(PMSG_RECV_DC_OTHER_CHANNEL * aRecv);
void DGMuBotSettingsSend(CGameObject &Obj, char* szName, BYTE* lpSettings);
void DGMuBotOptionRecv(MUBOT_SETTINGS_SEND* lpMsg);

extern int gMapSrvGroupOnlineServer;


#endif // _GAMEPROTOCOL_H
